[package]
name = "fileserver-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11"
tokio = { version = "1.47", features = ["full"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
sea-orm = { version = "1.1", features = [ "sqlx-sqlite", "runtime-tokio-rustls", "macros" ] }
sea-orm-migration = { version = "1.1", features = [ "sqlx-sqlite", "runtime-tokio-rustls" ] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.17.0", features = ["v7", "serde"] }
migration = { path = "migration" }

slog = "2.7"
slog-term = "2.9"
slog-async = "2.8"
slog-json = "2.6"
futures-util = "0.3"
